# Generated by Django 5.1 on 2024-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingilizcha', models.CharField(max_length=100, verbose_name='Ingilizcha')),
                ('uzbekcha', models.CharField(max_length=100, verbose_name='Uzbekcha')),
            ],
        ),
    ]
